# make sure the vol directory is owned by the user otherwise permission problems
version:  '3'
services:
    ml_python:
        build: ./
        container_name: ml_python
        ports:
            - 8888:8888
        volumes:
            - ./vol:/home/jovyan
        command: "start-notebook.sh"
